Repository prgrms-fe-devcourse/FES-5-Project2-TEAM-3, pull requests merged in 2025-07, with the labels that each got.

#13 style : 기본 폰트 및 색상 변수 설정
  ottogether/index.html
  ottogether/src/styles/_base.css
  ottogether/src/styles/_theme.css
  ottogether/src/styles/_utils.css
  ottogether/src/styles/common.css
Labels: inProgress

#14 FEAT : App.tsx
  ottogether/src/App.tsx
Labels: done

#15 feat : router 기능 및 NotFound 페이지 (#12)
  ottogether/package-lock.json
  ottogether/package.json
  ottogether/public/notFound.png
  ottogether/src/App.tsx
  ottogether/src/pages/NotFound/NotFound.module.css
  ottogether/src/pages/NotFound/NotFound.tsx
  ottogether/src/router.tsx
Labels: done

#16 Feature/register 회원가입 form 추가 (#3)
  ottogether/package-lock.json
  ottogether/package.json
  ottogether/src/assets/icons/eye-slash.svg
  ottogether/src/assets/icons/eye.svg
  ottogether/src/assets/icons/key-square.svg
  ottogether/src/assets/icons/sms.svg
  ottogether/src/assets/icons/user-square.svg
  ottogether/src/assets/register-character.png
  ottogether/src/pages/Register/Register.module.css
  ottogether/src/pages/Register/Register.tsx
  ottogether/vite.config.ts
Labels: inProgress

#19 Feature/Header 기본 기능 구현
  ottogether/package-lock.json
  ottogether/package.json
  ottogether/src/App.tsx
  ottogether/src/assets/icons/notification.svg
  ottogether/src/assets/icons/search-black.svg
  ottogether/src/assets/icons/search-white.svg
  ottogether/src/assets/logo.svg
  ottogether/src/layout/Header.module.css
  ottogether/src/layout/Header.tsx
  ottogether/src/layout/Layout.tsx
  ottogether/src/pages/Home/Home.tsx
  ottogether/src/router.tsx
  ottogether/src/router/router.tsx
  ottogether/src/router/routes.ts
Labels: inProgress

#20 feat : header / footer layout 정리
  ottogether/public/Logo.svg
  ottogether/src/App.tsx
  ottogether/src/assets/logo.svg
  ottogether/src/components/footer/Footer.module.css
  ottogether/src/layout/Footer.module.css
  ottogether/src/layout/Footer.tsx
  ottogether/src/layout/Header.tsx
  ottogether/src/layout/Layout.tsx
Labels: done

#21 supabase 연동 및 quotes 유틸 함수 작성
  ottogether/src/App.tsx
  ottogether/src/supabase/supabase.ts
  ottogether/src/supabase/supabase.type.ts
  ottogether/src/util/getQuote.ts
  ottogether/src/vite-env.d.ts
Labels: inProgress

#25 feat : memberCard Component
  .gitignore
  ottogether/public/Chevron_right.svg
  ottogether/src/components/member/MemberCard.module.css
  ottogether/src/components/member/MemberCard.tsx
  ottogether/src/components/review_/SupaData.tsx
  ottogether/src/components/review_/supabase.type.tsx
  ottogether/src/util/formatDate.tsx
Labels: inProgress

#28 Feature/member card son
  ottogether/src/components/member/MemberCard.tsx
  ottogether/src/components/review_/supabase.type.tsx
Labels: done

#29 feat : 로그인 + 아이디/ 비번 찾기 (#7)
  ottogether/src/assets/icons/close.svg
  ottogether/src/assets/icons/phone-white.svg
  ottogether/src/assets/icons/sms-white.svg
  ottogether/src/assets/icons/user-square-white.svg
  ottogether/src/assets/login-character.png
  ottogether/src/components/FindId/FindId.module.css
  ottogether/src/components/FindId/FindId.tsx
  ottogether/src/components/FindPassword/FindPassword.module.css
  ottogether/src/components/FindPassword/FindPassword.tsx
  ottogether/src/pages/Login/Login.module.css
  ottogether/src/pages/Login/Login.tsx
  ottogether/src/router/router.tsx
Labels: inProgress

#33 Feature/Register - Supabase 통신 기능 추가 (#3, #6, #8)
  ottogether/src/assets/default-profile/default-avatar1.png
  ottogether/src/assets/default-profile/default-avatar2.png
  ottogether/src/assets/default-profile/default-avatar3.png
  ottogether/src/assets/default-profile/default-avatar4.png
  ottogether/src/assets/default-profile/default-header1.png
  ottogether/src/assets/default-profile/default-header2.png
  ottogether/src/assets/default-profile/default-header3.png
  ottogether/src/assets/default-profile/default-header4.png
  ottogether/src/lib/defaultProfile.ts
  ottogether/src/lib/errorCodes.ts
  ottogether/src/pages/Register/Register.module.css
  ottogether/src/pages/Register/Register.tsx
  ottogether/src/pages/Register/RegisterDetail.module.css
  ottogether/src/pages/Register/RegisterDetail.tsx
  ottogether/src/pages/Register/RegisterProfile.module.css
  ottogether/src/pages/Register/RegisterProfile.tsx
  ottogether/src/supabase/auth/authRegister.ts
  ottogether/src/supabase/auth/checkNickname.ts
  ottogether/src/supabase/auth/getUserInfo.ts
  ottogether/src/supabase/storage/uploadImage.ts
  ottogether/src/supabase/supabase.type.ts
  ottogether/src/supabase/upsertTable.ts
  ottogether/src/util/formatPhoneNumber.ts
  ottogether/src/util/getRandomProfile.ts
Labels: done

#51 Feature/search OTT / Genre Selector 컴포넌트로 분리 & 검색 결과창 기본 골격 및 라우터 작업
  ottogether/src/components/Search/FilterPanel.module.css
  ottogether/src/components/Search/FilterPanel.tsx
  ottogether/src/components/Search/GenreSelector.module.css
  ottogether/src/components/Search/GenreSelector.tsx
  ottogether/src/components/Search/OttSelector.module.css
  ottogether/src/components/Search/OttSelector.tsx
  ottogether/src/pages/Register/RegisterDetail.module.css
  ottogether/src/pages/Register/RegisterDetail.tsx
  ottogether/src/pages/SearchResult/SearchResult.module.css
  ottogether/src/pages/SearchResult/SearchResult.tsx
  ottogether/src/router/router.tsx
Labels: inProgress

#57 bug : RegisterProfile 에서 값을 입력할 경우 저장이 안되는 이슈 해결 (#55)
  ottogether/src/pages/Register/RegisterProfile.tsx
  ottogether/src/supabase/supabase.ts
  ottogether/src/supabase/upsertTable.ts
Labels: done

#62 feature/api tmdb 함수, 홈페이지
  ottogether/src/components/movieCard/MovieCard.module.css
  ottogether/src/components/movieCard/MovieCard.tsx
  ottogether/src/components/movieCard/MovieList.module.css
  ottogether/src/components/movieCard/MovieList.tsx
  ottogether/src/components/movieCard/SectionGroup.tsx
  ottogether/src/lib/data.ts
  ottogether/src/pages/Home/Home.tsx
  ottogether/src/supabase/supabase.type.ts
  ottogether/src/tmdbApi/fetchGenres.ts
  ottogether/src/tmdbApi/fetchMoviesByGenre.ts
  ottogether/src/tmdbApi/fetchPopular.ts
  ottogether/src/tmdbApi/getMovieDetail.ts
  ottogether/src/tmdbApi/getMovieProvider.ts
  ottogether/src/tmdbApi/index.ts
  ottogether/src/tmdbApi/movie.type.ts
  ottogether/src/util/toggleFavoriteMovie.ts
Labels: done

#63 feat : Login - 유저 상태 저장 #7
  ottogether/src/App.tsx
  ottogether/src/components/FindPassword/FindPassword.module.css
  ottogether/src/contexts/AuthProvider.tsx
  ottogether/src/contexts/userContexts.tsx
  ottogether/src/pages/Login/Login.tsx
Labels: inProgress

#65 Feature/search 검색창 및 검색 필터 컴포넌트 구현
  ottogether/package.json
  ottogether/src/assets/icons/filter-off.svg
  ottogether/src/assets/icons/filter-on.svg
  ottogether/src/components/Search/FilterPanel.module.css
  ottogether/src/components/Search/FilterPanel.tsx
  ottogether/src/components/Search/GenreSelector.module.css
  ottogether/src/components/Search/GenreSelector.tsx
  ottogether/src/components/Search/OttSelector.module.css
  ottogether/src/components/Search/OttSelector.tsx
  ottogether/src/components/Search/SearchBar.module.css
  ottogether/src/components/Search/SearchBar.tsx
  ottogether/src/layout/Header.module.css
  ottogether/src/layout/Header.tsx
  ottogether/src/pages/Register/RegisterDetail.tsx
  ottogether/src/pages/SearchResult/SearchResult.tsx
  ottogether/src/util/isDefaultFilter.ts
Labels: inProgress

#67 Feature/home jin
  ottogether/src/pages/Home/Home.tsx
  ottogether/src/tmdbApi/fetchGenres.ts
  ottogether/src/tmdbApi/fetchMoviesByGenre.ts
  ottogether/src/tmdbApi/fetchPopular.ts
  ottogether/src/tmdbApi/getMovieDetail.ts
  ottogether/src/tmdbApi/getMovieProvider.ts
  ottogether/vite.config.ts
Labels: inProgress

#70 feat : RegisterProfile Skip Button 클릭 시 랜덤 프로필/헤더를 저장하도록 수정 (#66)
  ottogether/src/pages/Register/RegisterProfile.tsx
Labels: done

#73 feature/home
  ottogether/src/components/movieCard/MovieList.module.css
  ottogether/src/components/movieCard/MovieList.tsx
  ottogether/src/components/movieCard/SectionGroup.tsx
  ottogether/src/pages/Home/Hero.module.css
  ottogether/src/pages/Home/Hero.tsx
  ottogether/src/pages/Home/Home.module.css
  ottogether/src/pages/Home/Home.tsx
  ottogether/src/pages/Quotes/QuotesPage.tsx
  ottogether/src/tmdbApi/movie.type.ts
Labels: inProgress

#74 ReviewCreate 기능 80% 구현
  ottogether/src/components/member/MemberCard.tsx
  ottogether/src/components/reviewCard/ReviewCreate.module.css
  ottogether/src/components/reviewCard/ReviewCreate.tsx
  ottogether/src/components/reviewCard/SupaData.ts
  ottogether/src/components/reviewCard/supabase.type.ts
  ottogether/src/pages/Review_/Review.tsx
Labels: backlog

#76 feat : MyPage 틀 작성 #39
  ottogether/src/assets/icons/settings.svg
  ottogether/src/components/inMyPage/CreatedQuotes.tsx
  ottogether/src/components/inMyPage/CreatedReviews.tsx
  ottogether/src/components/inMyPage/LikedQuotes.tsx
  ottogether/src/components/inMyPage/LikedReviews.tsx
  ottogether/src/components/inMyPage/LikedVideoContents.tsx
  ottogether/src/components/inMyPage/Settings.tsx
  ottogether/src/pages/MyPage/MyPage.module.css
  ottogether/src/pages/MyPage/MyPage.tsx
  ottogether/src/router/router.tsx
Labels: inProgress

#75 Feature/search 검색 탭 기능 구현 (#37)
  ottogether/index.html
  ottogether/public/favicon.svg
  ottogether/public/ott/Watcha.png
  ottogether/src/components/Search/SearchTab.module.css
  ottogether/src/components/Search/SearchTab.tsx
  ottogether/src/lib/data.ts
  ottogether/src/pages/SearchResult/SearchResult.module.css
  ottogether/src/pages/SearchResult/SearchResult.tsx
Labels: inProgress

#77 feat : reviewCreate 리뷰 작성 기능 구현
  ottogether/public/close.svg
  ottogether/public/edit.svg
  ottogether/public/trashcan.svg
  ottogether/src/components/reviewCard/ReviewCard.tsx
  ottogether/src/components/reviewCard/ReviewCreate.tsx
  ottogether/src/components/reviewDetailPopup/ReviewDetailPopup.module.css
  ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx
  ottogether/src/pages/Review_/Review.module.css
  ottogether/src/pages/Review_/Review.tsx
Labels: done
