Repository prgrms-fe-devcourse/FES-5-Project2-TEAM-3, pull requests merged in 2025-08, with the labels that each got.

#80 Feature/search 영화/시리즈 검색 결과 탭 구현
  ottogether/public/default-poster.png
  ottogether/src/components/Search/SearchBar.tsx
  ottogether/src/components/Search/SearchMovie.module.css
  ottogether/src/components/Search/SearchMovie.tsx
  ottogether/src/components/Search/SearchNotFound.module.css
  ottogether/src/components/Search/SearchNotFound.tsx
  ottogether/src/components/Search/SearchSeries.tsx
  ottogether/src/components/Search/SearchTab.module.css
  ottogether/src/components/Search/SearchTab.tsx
  ottogether/src/components/movieCard/MovieCard.module.css
  ottogether/src/components/movieCard/MovieCard.tsx
  ottogether/src/components/movieCard/MovieList.module.css
  ottogether/src/components/movieCard/MovieList.tsx
  ottogether/src/lib/data.ts
  ottogether/src/lib/genreMap.ts
  ottogether/src/lib/ottNameMap.ts
  ottogether/src/pages/SearchResult/SearchResult.tsx
  ottogether/src/supabase/review/getAvgRating.ts
  ottogether/src/tmdbApi/movie.type.ts
  ottogether/src/tmdbApi/series.type.ts
  ottogether/src/util/applyFilters.ts
  ottogether/src/util/getGenreId.ts
Labels: inProgress

#82 feat : 댓글 수정 기능 구현
  ottogether/src/components/reviewDetailPopup/ReviewDetailPopup.module.css
  ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx
  ottogether/src/pages/Members/Members.tsx
Labels: done

#83 style : header 너비 변경
  ottogether/src/layout/Header.module.css
Labels: done

#89 Feature/header merge 후 충돌난 CSS 조정
  ottogether/public/ott/PrimeVideo.png
  ottogether/src/components/inMyPage/Settings.module.css
  ottogether/src/layout/Header.module.css
  ottogether/src/lib/data.ts
  ottogether/src/lib/ottNameMap.ts
Labels: done

#90 [Feature/search] Quote 검색 컴포넌트 추가
  ottogether/src/components/Quotes/QuoteCard.tsx
  ottogether/src/components/Search/SearchQuote.module.css
  ottogether/src/components/Search/SearchQuote.tsx
  ottogether/src/components/Search/SearchTab.module.css
  ottogether/src/components/Search/SearchTab.tsx
  ottogether/src/pages/Home/Home.tsx
  ottogether/src/pages/Quotes/QuotesPage.tsx
  ottogether/src/supabase/quotes/searchQuotes.ts
  ottogether/src/supabase/supabase.type.ts
Labels: inProgress

#96 feat : MyPage 기능 일부 구현 (#39)
  ottogether/src/assets/welcome-character.png
  ottogether/src/components/inMyPage/MySettings/DeleteAccountSection.tsx
  ottogether/src/components/inMyPage/MySettings/NotificationSection.tsx
  ottogether/src/components/inMyPage/MySettings/PasswordSection.tsx
  ottogether/src/components/inMyPage/MySettings/ProfileSettings.module.css
  ottogether/src/components/inMyPage/MySettings/ProfileSettings.tsx
  ottogether/src/components/inMyPage/MySettings/Settings.module.css
  ottogether/src/components/inMyPage/MySettings/Settings.tsx
  ottogether/src/components/inMyPage/MySettings/SystemSettings.module.css
  ottogether/src/components/inMyPage/MySettings/SystemSettings.tsx
  ottogether/src/components/inMyPage/MySettings/ToggoleSwitch.tsx
  ottogether/src/components/inMyPage/MySettings/VisibilitySection.tsx
  ottogether/src/components/inMyPage/ProfileBox.module.css
  ottogether/src/components/inMyPage/ProfileBox.tsx
  ottogether/src/components/inMyPage/Settings.module.css
  ottogether/src/components/inMyPage/Settings.tsx
  ottogether/src/components/inMyPage/ShowDefault.module.css
  ottogether/src/components/inMyPage/ShowDefault.tsx
  ottogether/src/pages/MyPage/MyPage.module.css
  ottogether/src/pages/MyPage/MyPage.tsx
Labels: inProgress

#101 Feature/home detail jin
  ottogether/src/components/movieCard/MovieList.tsx
  ottogether/src/components/movieCard/SectionGroup.tsx
  ottogether/src/pages/Home/Home.tsx
  ottogether/src/tmdbApi/fetchContentByGenre.ts
  ottogether/src/tmdbApi/fetchGenres.ts
  ottogether/src/tmdbApi/fetchMoviesByGenre.ts
  ottogether/src/tmdbApi/fetchTvSeriesByGenre.ts
  ottogether/src/tmdbApi/getMovieProvider.ts
  ottogether/src/tmdbApi/movie.type.ts
  ottogether/src/tmdbApi/series.type.ts
Labels: inProgress

#100 Feature/search 검색 결과 페이지 추가 구현
  ottogether/src/assets/icons/warning.svg
  ottogether/src/assets/notfound-character.png
  ottogether/src/components/Search/SearchMovie.tsx
  ottogether/src/components/Search/SearchNotFound.module.css
  ottogether/src/components/Search/SearchNotFound.tsx
  ottogether/src/components/Search/SearchQuote.module.css
  ottogether/src/components/Search/SearchQuote.tsx
  ottogether/src/components/Search/SearchSeries.tsx
  ottogether/src/components/Search/SearchTab.module.css
  ottogether/src/components/Search/SearchTab.tsx
  ottogether/src/components/Search/SearchUser.tsx
  ottogether/src/components/member/MemberCard.module.css
  ottogether/src/components/member/MemberCard.tsx
Labels: done

#107 Feature/home detail jin 메인 페이지 디테일 수정, 쿼츠 css수정
  ottogether/src/components/Quotes/QuoteCard.module.css
  ottogether/src/components/Quotes/QuoteCard.tsx
  ottogether/src/components/movieCard/MovieCard.tsx
  ottogether/src/layout/Footer.tsx
  ottogether/src/pages/Home/Hero.tsx
  ottogether/src/tmdbApi/fetchPopular.ts
Labels: done

#109 feat : MyPage - Notification 기본 틀 구현
  ottogether/src/components/Notifications/Notifications.module.css
  ottogether/src/components/Notifications/Notifications.tsx
  ottogether/src/components/inMyPage/MySettings/DeleteAccountModal.tsx
  ottogether/src/components/inMyPage/MySettings/PasswordModal.module.css
  ottogether/src/components/inMyPage/MySettings/PasswordModal.tsx
  ottogether/src/components/inMyPage/MySettings/PasswordSection.tsx
  ottogether/src/components/inMyPage/MySettings/SystemSettings.module.css
  ottogether/src/components/inMyPage/MySettings/SystemSettings.tsx
  ottogether/src/components/inMyPage/Notifications.tsx
  ottogether/src/pages/MyPage/MyPage.tsx
  ottogether/src/supabase/supabase.type.ts
  ottogether/src/util/createNotifications.ts
Labels: inProgress

#115 Feature/header Header 아이콘 사이즈 조정, 페이지 이동 시 햄버거 메뉴 닫히도록 수정
  ottogether/src/layout/Header.module.css
  ottogether/src/layout/Header.tsx
Labels: done

#117 style : Member Page CSS 스타일 수정 (#111)
  ottogether/src/pages/Members/Members.module.css
  ottogether/src/pages/Members/Members.tsx
Labels: done

#118 contentsDetailPage 구현 중
  ottogether/public/emptyFavorite.svg
  ottogether/public/fullFavorite.svg
  ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx
  ottogether/src/pages/MovieDetail/MovieDetail.module.css
  ottogether/src/pages/MovieDetail/MovieDetail.tsx
  ottogether/src/pages/MovieDetail/ProfileList.module.css
  ottogether/src/pages/MovieDetail/ProfileList.tsx
  ottogether/src/pages/MovieDetail/RatingBarChart.module.css
  ottogether/src/pages/MovieDetail/RatingBarChart.tsx
  ottogether/src/pages/Review_/Review.tsx
  ottogether/src/supabase/supabase.type.ts
Labels: backlog

#120 feat : 회원가입 시 알림 설정 정보를 저장할 수 있는 함수 추가 (#113)
  ottogether/src/components/member/MemberCard.tsx
  ottogether/src/pages/Members/Members.tsx
  ottogether/src/pages/Register/RegisterDetail.tsx
  ottogether/src/supabase/supabase.type.ts
Labels: done

#129 fix : MyPage - profile 에러 수정
  ottogether/src/components/Notifications/Notifications.tsx
  ottogether/src/components/Quotes/QuoteCard.tsx
  ottogether/src/components/inMyPage/CreatedReviews.tsx
  ottogether/src/components/inMyPage/LikedReviews.tsx
  ottogether/src/components/inMyPage/MyPageReviews.module.css
  ottogether/src/components/inMyPage/MySettings/DeleteAccountModal.tsx
  ottogether/src/components/inMyPage/MySettings/NotificationSection.tsx
  ottogether/src/components/reviewCard/ReviewCard.tsx
  ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx
  ottogether/src/pages/MyPage/MyPage.tsx
  ottogether/src/pages/Quotes/QuotesPage.module.css
  ottogether/src/pages/Quotes/QuotesPage.tsx
  ottogether/src/pages/Review_/Review.tsx
  ottogether/src/util/createNotifications.ts
Labels: done

#133 fix : SearchUser -> UserCard Props 변경
  ottogether/src/components/Search/SearchUser.tsx
  ottogether/src/supabase/profile/searchUserProfile.ts
Labels: done

#135 style : Members 페이지 CSS 재조정
  ottogether/src/components/member/MemberCard.module.css
  ottogether/src/pages/Home/Home.tsx
  ottogether/src/pages/Members/Members.module.css
Labels: done

#138 fix : 파일 경로 대/소문자 수정
  ottogether/src/pages/Review_/Review.tsx
Labels: done

#146 feat : MyPage - Notification 기능 구현
  ottogether/src/components/Notifications/Notifications.module.css
  ottogether/src/components/Notifications/Notifications.tsx
  ottogether/src/components/inMyPage/LikedReviews.tsx
  ottogether/src/components/inMyPage/MyPageVideos.module.css
  ottogether/src/components/inMyPage/MySettings/NotificationSection.tsx
  ottogether/src/components/inMyPage/ProfileBox.module.css
  ottogether/src/components/inMyPage/ProfileBox.tsx
  ottogether/src/pages/MyPage/MyPage.tsx
  ottogether/src/util/createNotifications.ts
Labels: inProgress

#150 fix : Home에서 양옆 화살표 아이콘 깨지는 것 수정
  ottogether/src/components/movieCard/MovieList.tsx
Labels: done

#160 Feature/error Home MovieCard Skeleton 처리
  ottogether/src/components/movieCard/MovieCardSkeleton.module.css
  ottogether/src/components/movieCard/MovieCardSkeleton.tsx
  ottogether/src/components/movieCard/MovieList.tsx
Labels: done

#172 Feature/error QA하면서 발견한 수정
  ottogether/src/components/Quotes/QuoteCard.module.css
  ottogether/src/components/Quotes/QuoteCard.tsx
  ottogether/src/components/inMyPage/MySettings/ProfileSettings.module.css
  ottogether/src/components/inMyPage/MySettings/ProfileSettings.tsx
  ottogether/src/components/inMyPage/ProfileBox.module.css
  ottogether/src/components/inMyPage/ProfileBox.tsx
  ottogether/src/components/member/MemberCard.module.css
  ottogether/src/components/member/MemberCard.tsx
  ottogether/src/components/movieCard/MovieCard.tsx
  ottogether/src/components/reviewCard/ReviewCard.module.css
  ottogether/src/components/reviewCard/ReviewCard.tsx
  ottogether/src/components/reviewCard/ReviewCreate.module.css
  ottogether/src/components/reviewCard/ReviewCreate.tsx
  ottogether/src/components/reviewCard/SmallReviewCard/SmallReviewCard.module.css
  ottogether/src/components/reviewCard/SmallReviewCard/SmallReviewCard.tsx
  ottogether/src/components/reviewDetailPopup/ReviewDetailPopup.module.css
  ottogether/src/components/reviewDetailPopup/reviewDetailPopup.tsx
  ottogether/src/pages/ContentsDetail/ContentsDetail.module.css
  ottogether/src/pages/ContentsDetail/ContentsDetail.tsx
  ottogether/src/pages/Home/Home.tsx
  ottogether/src/pages/MovieDetail/MovieDetail.tsx
  ottogether/src/pages/MyPage/MyPage.module.css
  ottogether/src/pages/NotFound/NotFound.module.css
  ottogether/src/pages/Review_/Review.tsx
  ottogether/src/router/routes.ts
  ottogether/src/supabase/notifications/useNotifications.ts
  ottogether/src/util/getQuote.ts
  ottogether/vercel.json
Labels: done

#188 fix : MyPage - 리뷰 모달 관련 오류 수정
  ottogether/src/components/inMyPage/CreatedReviews.tsx
  ottogether/src/components/inMyPage/LikedReviews.tsx
  ottogether/src/pages/Review_/Review.tsx
Labels: done
